# task_manager.py
# Generated by HDS6 Cognitive Core
# Unified CLI for maintaining the HDS6 Task Database

import argparse
import os
import shutil
import re
import sys
from pathlib import Path

# Додаємо шлях до agent для імпорту vox
sys.path.append(str(Path(__file__).parent.parent / "agent"))
try:
    from vox import VoxService
except ImportError:
    VoxService = None

vox = VoxService() if VoxService else None

def create_task(task_id: str, title: str, priority: str = "MEDIUM"):
    """ Generates a fresh YAML Front-Matter task """
    base_dir = Path(__file__).parent.resolve() / "tasks" / "active"
    base_dir.mkdir(parents=True, exist_ok=True)
    
    safe_title = re.sub(r'[^a-zA-Z0-9_\-]', '_', title.lower().replace(' ', '-'))
    filename = f"{task_id}-{safe_title}.md"
    file_path = base_dir / filename
    
    template = f"""---
id: "{task_id}"
title: "{title}"
status: "in_progress"
priority: "{priority.upper()}"
dependencies: []
output_module: ""
---

# Objective
Describe the goals and expected outcomes of this task.

## Key Actions
- [ ] Step 1
- [ ] Step 2
"""
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(template)
    
    msg = f"HDS6 TaskManager: Created task {task_id}: {title}"
    print(msg)
    if vox:
        vox.speak(f"New task created. Task {task_id}: {title}", "INFO")

def archive_tasks():
    """ Sweeps tasks where status is explicitly done or 100% """
    base_path = Path(__file__).parent.resolve() / "tasks" / "active"
    archive_path = base_path / ".archive"
    archive_path.mkdir(exist_ok=True)
    
    moved_count = 0
    print("HDS6 TaskManager - Scanning active workspace for completed tasks...")
    
    # Matches `status: "done"`, `status: done`, `status: 'done'`, etc.
    status_regex = re.compile(r'^status:\s*["\']?(done|100|completed)["\']?', re.MULTILINE | re.IGNORECASE)
    
    # Fallback for previous legacy formatting in old docs just in case
    legacy_regex = re.compile(r'\[PROGRESS: 100%\]|PROGRESS: 100%')
    
    for file_path in base_path.glob("*.md"):
        try:
            with open(file_path, "r", encoding="utf-8") as f:
                content = f.read(2048) # Parse YAML front matter limit
            
            if status_regex.search(content) or legacy_regex.search(content):
                dest = archive_path / file_path.name
                shutil.move(str(file_path), str(dest))
                print(f"Archived: {file_path.name}")
                moved_count += 1
                if vox:
                    # Озвучка для кожної архівованої таски (опціонально, але краще підсумок)
                    pass
        except Exception as e:
            print(f"Error analyzing {file_path.name}: {e}")
    
    summary = f"HDS6 TaskManager: Operation finished. Automated archival of {moved_count} tasks."
    print(summary)
    if vox and moved_count > 0:
        vox.speak(f"Archival complete. {moved_count} tasks moved to archive.", "INFO")
    elif vox:
        vox.speak("Archival scan complete. No tasks were moved.", "INFO")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="HDS6 Task Standard CLI")
    subparsers = parser.add_subparsers(dest="command")
    
    # Command: create
    create_parser = subparsers.add_parser("create", help="Boilerplates a new YAML front-matter task ticket")
    create_parser.add_argument("id", help="Standardised Task ID (e.g. 050)")
    create_parser.add_argument("title", help="Human-readable title")
    create_parser.add_argument("--priority", default="MEDIUM", help="Priority scaling parameter")
    
    # Command: archive
    archive_parser = subparsers.add_parser("archive", help="Sweeps tasks carrying a 'done' semantic payload.")
    
    args = parser.parse_args()
    
    if args.command == "create":
        create_task(args.id, args.title, args.priority)
    elif args.command == "archive":
        archive_tasks()
    else:
        parser.print_help()
